### ISSUE TITLE
ALSA plugin Wiki need to be updated to reflect the merge of the AMIXER/ALSACTL plugins

### ISSUE THREAD

**Issue by sguiriec** [01org/parameter-framework-plugins-alsa#12]
The Wiki is not updated according to the latest code with the merge of the AMIXER and ALSACTL plugins.

**Comment by dawagner** [comment]
It should be fixed now. @sguiriec @Makohoek please check and close if you are ok with the changes.

**Comment by Makohoek** [comment]
Seems good to me.
:+1: 

Letting @sguiriec close the issue if he approves.

**Comment by gdenneul** [comment]
:+1:
